# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GyazoUploader
                                 A QGIS plugin
 Plug-in to upload QGIS maps to Gyazo
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-01-18
        copyright            : (C) 2025 by yuiseki
        email                : yuiseki@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GyazoUploader class from file GyazoUploader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .gyazo_uploader import GyazoUploader
    return GyazoUploader(iface)
